Mememotron/config/routes.rb
Mememotron::Application.routes.draw do
  resources :memes
  resources :crypto_currencies

end

Mememotron/app/models/crypto_currency.rb
class CryptoCurrency < ActiveRecord::Base
  attr_accessible :description
end

Mememotron/app/models/meme.rb
class Meme < ActiveRecord::Base
  attr_accessible :name, :url

  validates :name, presence: true
end

Mememotron/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # before_filter :authenticate!, only: [:create]

  protected

  def authenticate!
    authenticate_or_request_with_http_basic do |username, password|
      username == "crypto" && password == "currency"
    end
  end
end

Mememotron/app/controllers/crypto_currencies_controller.rb
class CryptoCurrenciesController < ApplicationController
  before_filter :hide_identity

  def hide_identity
    if params[:name] == "Satoshi Nakamoto"
      render json: { error: "Don't use my real name." }, status: 422
    end
  end
  private :hide_identity

  # def create_bitcoin
  #   # A new developer adds this action.
  #   # do I require `#hide_identity`?
  #   #
  #   # When I'm refactored to BitcoinsController#create
  #   # will the developer remember to `#hide_identity`?
  #   render json: { fail: "Free lunch!?" }
  # end

  def index
    @crypto_currencies = CryptoCurrency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crypto_currencies }
    end
  end

  def show
    @crypto_currency = CryptoCurrency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crypto_currency }
    end
  end

  def new
    @crypto_currency = CryptoCurrency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crypto_currency }
    end
  end

  def edit
    @crypto_currency = CryptoCurrency.find(params[:id])
  end

  def create
    @crypto_currency = CryptoCurrency.new(params[:crypto_currency])

    respond_to do |format|
      if @crypto_currency.save
        format.html { redirect_to @crypto_currency, notice: 'Crypto currency was successfully created.' }
        format.json { render json: @crypto_currency, status: :created, location: @crypto_currency }
      else
        format.html { render action: "new" }
        format.json { render json: @crypto_currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @crypto_currency = CryptoCurrency.find(params[:id])

    respond_to do |format|
      if @crypto_currency.update_attributes(params[:crypto_currency])
        format.html { redirect_to @crypto_currency, notice: 'Crypto currency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crypto_currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @crypto_currency = CryptoCurrency.find(params[:id])
    @crypto_currency.destroy

    respond_to do |format|
      format.html { redirect_to crypto_currencies_url }
      format.json { head :no_content }
    end
  end
end

Mememotron/app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_filter :id_required!, only: [:index]

  def index
    @memes = Meme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memes }
    end
  end

  def id_required!
    unless params[:api_id]
      message = "you need an api_id"
      render json: { error: message}, status: 401
    end
  end
  private :id_required!

  def show
    @meme = Meme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meme }
    end
  end

  def new
    @meme = Meme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meme }
    end
  end

  def edit
    @meme = Meme.find(params[:id])
  end

  def create
    @meme = Meme.new(params[:meme])

    respond_to do |format|
      if @meme.save
        format.html { redirect_to @meme, notice: 'Meme was successfully created.' }
        format.json { render json: @meme, status: :created, location: @meme }
      else
        format.html { render action: "new" }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @meme = Meme.find(params[:id])

    respond_to do |format|
      if @meme.update_attributes(params[:meme])
        format.html { redirect_to @meme, notice: 'Meme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meme = Meme.find(params[:id])
    @meme.destroy

    respond_to do |format|
      format.html { redirect_to memes_url }
      format.json { head :no_content }
    end
  end
end

Mememotron/app/helpers/application_helper.rb
module ApplicationHelper
end

Mememotron/app/helpers/memes_helper.rb
module MemesHelper
end

Mememotron/app/views/crypto_currencies/_form.html.haml
= form_for @crypto_currency do |f|
  - if @crypto_currency.errors.any?
    #error_explanation
      %h2= "#{pluralize(@crypto_currency.errors.count, "error")} prohibited this crypto_currency from being saved:"
      %ul
        - @crypto_currency.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

Mememotron/app/views/crypto_currencies/edit.html.haml
%h1 Editing crypto_currency

= render 'form'

= link_to 'Show', @crypto_currency
\|
= link_to 'Back', crypto_currencies_path

Mememotron/app/views/crypto_currencies/index.html.haml
%h1 Listing crypto_currencies

%table
  %tr
    %th Description
    %th
    %th
    %th

  - @crypto_currencies.each do |crypto_currency|
    %tr
      %td= crypto_currency.description
      %td= link_to 'Show', crypto_currency
      %td= link_to 'Edit', edit_crypto_currency_path(crypto_currency)
      %td= link_to 'Destroy', crypto_currency, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Crypto currency', new_crypto_currency_path

Mememotron/app/views/crypto_currencies/new.html.haml
%h1 New crypto_currency

= render 'form'

= link_to 'Back', crypto_currencies_path

Mememotron/app/views/crypto_currencies/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @crypto_currency.description

= link_to 'Edit', edit_crypto_currency_path(@crypto_currency)
\|
= link_to 'Back', crypto_currencies_path

Mememotron/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mememotron</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Mememotron/app/views/memes/_form.html.haml
= form_for @meme do |f|
  - if @meme.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meme.errors.count, "error")} prohibited this meme from being saved:"
      %ul
        - @meme.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

Mememotron/app/views/memes/edit.html.haml
%h1 Editing meme

= render 'form'

= link_to 'Show', @meme
\|
= link_to 'Back', memes_path

Mememotron/app/views/memes/index.html.haml
%h1 Listing memes

%table
  %tr
    %th Name
    %th Url
    %th
    %th
    %th

  - @memes.each do |meme|
    %tr
      %td= meme.name
      %td= meme.url
      %td= link_to 'Show', meme
      %td= link_to 'Edit', edit_meme_path(meme)
      %td= link_to 'Destroy', meme, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Meme', new_meme_path

Mememotron/app/views/memes/new.html.haml
%h1 New meme

= render 'form'

= link_to 'Back', memes_path

Mememotron/app/views/memes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @meme.name
%p
  %b Url:
  = @meme.url

= link_to 'Edit', edit_meme_path(@meme)
\|
= link_to 'Back', memes_path